### ISSUE TITLE
Use newly created ral project when viable 

### ISSUE THREAD

**Issue by teburd** [imxrt-rs/imxrt-ral#21]
From @adamgreig 
https://github.com/adamgreig/ral-registers

**Comment by mciantyre** [comment]
#24 includes an integration with the const generic peripheral instances. Since [peripheral instance APIs are behind an `impl` block](https://github.com/mciantyre/imxrt-ral/commit/d43cdc5b657b48bda52421a6cbb3b8a349c834c9), we can't directly use `reset_reg!` from ral-registers. If we accept #24, we'll need to maintain [our own version of the macro](https://github.com/mciantyre/imxrt-ral/commit/707b0651adf682316a2b24327551ddb2e1e474c2).

**Comment by teburd** [comment]
I don’t think this is valid anymore with the chip tool form, closing

**Comment by mciantyre** [comment]
For future readers: `raltool` produces a RAL that re-exports the `ral-registers` macros and register types.

A short-term note: since `raltool` can generate arrays of registers, we'd like `ral-register` macros to handle that. https://github.com/adamgreig/ral-registers/pull/5 tracks that support.
