### ISSUE TITLE
Update other packages such as imxrt-hal to 0.5.0.

### ISSUE THREAD

**Issue by Sandvoxel** [imxrt-rs/imxrt-ral#28]
I am working with the latest version imxrt-ral in my package for QSPI for eventual SDCard support as I am adding some of the missing const to Flexspi file. I would like to use teensy-bsp but as it stands right now the most recent version of imxrt-hal cannot build with 0.5.0 do to the breaking changes with the change to static instances of the IO types. I would be happy to make a CR for imxrt-ral and teensy-bsp to update them to the new ral version, but I may need some guidance of what I would need to fix. How would I go about updating this snippet of code from imxrt-hal would the PhantomData be required now that the types are split up.

```rust
/// An I2C builder that can build and I2C peripheral
pub struct Builder<M> {
    _module: PhantomData<M>,
    reg: ral::lpi2c::Instance,
    /// Frequency of the LPI2C source clock. This
    /// accounts for the divider.
    source_clock: ccm::Frequency,
}

impl<M> Builder<M>
where
    M: Unsigned,
{
    fn new(source_clock: ccm::Frequency, reg: ral::lpi2c::Instance) -> Self {
        Builder {
            _module: PhantomData,
            reg,
            source_clock,
        }
    }

    /// Builds an I2C peripheral from the SCL and SDA pins. The return
    /// is a configured I2C master running at 100KHz.
    pub fn build<SCL, SDA>(self, mut scl: SCL, mut sda: SDA) -> I2C<M>
    where
        SCL: i2c::Pin<Module = M, Signal = i2c::SCL>,
        SDA: i2c::Pin<Module = M, Signal = i2c::SDA>,
    {
        crate::iomuxc::i2c::prepare(&mut scl);
        crate::iomuxc::i2c::prepare(&mut sda);
        I2C::new(self.source_clock, self.reg)
    }
}
```

Here is a another snippet of code I was wondering about.
```rust
/// PWM peripheral handle
///
/// Most operations that could affect multiple submodules require
/// access to this handle.
pub struct Handle<M> {
    reg: Instance,
    _marker: PhantomData<M>,
}

/// A PWM submodule
///
/// A submodule may be consumed to create PWM pin instances
pub struct Submodule<M, S> {
    _marker: PhantomData<(M, S)>,
}

/// A PWM peripheral
///
/// The PWM peripheral is broken into
///
/// - the PWM master handle, `handle`,
/// - four submodules, numbered `0` through `3`.
///
/// The submodules are taken when you want to turn pins into
/// PWM outputs. The handle provides access to registers that
/// are shared across PWM submodules.
pub struct PWM<M> {
    /// The peripheral handle
    ///
    /// Methods that need access to peripheral-level registers, rather than
    /// just submodule-level registers, must have a mutable reference to
    /// the handle.
    pub handle: Handle<M>,
    /// Submodule 0
    pub sm0: Submodule<M, U0>,
    /// Submodule 1
    pub sm1: Submodule<M, U1>,
    /// Submodule 2
    pub sm2: Submodule<M, U2>,
    /// Submodule 3
    pub sm3: Submodule<M, U3>,
}
```
Sorry for all the Issues I would just prefer to use rust for my custom board.

**Comment by mciantyre** [comment]
I like that ambition. But, I'm not sure we should try to port today's imxrt-**hal** to use imxrt-**ral**'s main branch. imxrt-rs/imxrt-hal#121 proposes a similar update, but with many breaking changes, including breaking changes to those snippets above.

We're in (we've been in) a transition state, so I'm afraid using the unreleased RAL with the released Teensy 4 BSP isn't straightforward. Here's the approaches I can offer:

**🔵 pill: Stick with the released HAL and BSP**

Apply your RAL changes to the RAL's main branch, and submit them here. If they're non-breaking / fixing a bug, we'll backport them to [the 0.4 branch](https://github.com/imxrt-rs/imxrt-ral/tree/v0.4) and release. A `cargo update` in your project means that you'll see the RAL changes in the released HAL and BSP.

This approach gives up on using the latest RAL. But, you can keep using the released HAL, BSP, and things that depend on these two. I think this is the easier approach.

**🔴 pill: Jump on the cutting edge**

Pull down imxrt-rs/imxrt-hal#121, and start building your driver there. This is using (something that closely resembles) the RAL's main branch. The HAL should have all the updates you would need.

This approach gives up on using the released Teensy 4 BSP. Although there's no BSP right now, imxrt-rs/imxrt-hal#121 includes in-tree examples, and makes it easy to run them on the Teensy 4. This includes USB / serial logging to help with any driver debugging.

We still need RAL patches. imxrt-rs/imxrt-hal#121 is using [my fork of the RAL](https://github.com/mciantyre/imxrt-ral), so the changes would need to end up in a similar-looking fork. I still think making the changes _here_, in the main repo, would be best. I could get them into my fork for your usage.

I think this is the harder and riskier approach, since this is all new development and needs more coordination. But, you'll provide us with valuable feedback about the proposed HAL.

**Comment by Sandvoxel** [comment]
I will probably end up going with the red option. That said my I will need to do some more work as I have just been adding constant as I need them. I just did not want to have to jump through the rabbit hole I'd of registers all the way down. Also there is the need for me to write something to do logging but I'll see what I can do.

**Comment by mciantyre** [comment]
The red pill is now the default pill. imxrt-**hal** 0.5 uses imxrt-**ral** 0.5. Both are available on crates.io.

There's also a new teensy4-bsp that uses both of these crates. But now that [the imxrt-hal project](https://github.com/imxrt-rs/imxrt-hal) maintains hardware examples, I recommend developing drivers and hardware examples within that repo, instead of using teensy4-bsp. By developing drivers and hardware examples there, we can more easily use the work across chips, and debug / test across hardware.

Reach out separately if you'd like help upstreaming any imxrt-ral patches.
