### ISSUE TITLE
Incorrect bit width of `PINSEL` registers in FlexIO of `106x`

### ISSUE THREAD

**Issue by Finomnis** [imxrt-rs/imxrt-ral#40]
There is an irregularity in the 106x FlexIO.

Number of Pins:
- FlexIO1: 16
- FlexIO2: 32
- FlexIO3: 32

Consequently, the `PINSEL` registers in `SHIFTCTL` and `TIMCTL` are 4 bit wide.
Sadly, they **should** be 5 bit wide on FlexIO2 and FlexIO3. This makes half of the pins disfunctional.

**Comment by mciantyre** [comment]
The root cause seems to be SVD construction. At least with the 1062 SVD, FlexIO**2** and FlexIO**3** both derive from FlexIO**1**. Essentially, the SVD suggests that all three peripherals are the same.

I'm not sure what the process looks like to correct this in today's pipeline. I believe `svdtools` has the ability to "clone" peripheral blocks. Once that happens, we could apply patches to the cloned peripheral block to represents FlexIO**2**, then derive FlexIO**3** from FlexIO**2**.

**Comment by Finomnis** [comment]
I believe it would be fine to just use 5 bit width for all of them. At least I don't really see why not. If that makes it easier.

**Comment by mciantyre** [comment]
Good with me. Users will need to make sure they're not accessing invalid bits for their FlexIO**1** peripheral.

Now that I think about it: If we took the clone and patch approach, we would end up generating two distinct register blocks, and two distinct modules. This would hurt the naming consistency efforts in #37.
