### ISSUE TITLE
RT1180's LPUART looses significant features when forced to be the same ar RT1011

### ISSUE THREAD

**Issue by korken89** [imxrt-rs/imxrt-ral#55]
@teburd was a prophet in #52. I'm working on the LPUART now and the dropped registers makes it so it's not possible to implement the extended features on this LPUART that we need. :sweat_smile: 

@mciantyre is there someway to use `ForceCommonBlock` so that the "extra" registers are kept somehow? Or do we need to accept that RT1180 will have it's own LPUART block?

Moreover, I think we were just lucky but the new flags needed to setup the FIFO to the correct size were keptk.
I'll try to use the RT1180 without the `ForceCommonBlock` for now and see if I can get the LPUART to work. :rocket:

**Comment by mciantyre** [comment]
There's no harm in having a distinct LPUART block for the 1180. As long as the Rust symbols are all the same, the imxrt-hal `lpuart` driver will compile. Forcing a common block is a simple way to achieve that goal.

If we can't use the common functionality, then we can remove `ForceCommonBlock`. Then, if the 1180's LPUART block doesn't immediately compile with the imxrt-hal `lpuart` driver, we could try patching it with `svdtool` / `raltool` so that it builds.

---

> Moreover, I think we were just lucky but the new flags needed to setup the FIFO to the correct size were keptk.

Sorry, but could you explain more here? I'm aware that the 1180's LPUART FIFO is 4x larger than what we've seen on the other MCUs. A LPUART driver that expects a 4x smaller FIFO isn't taking advantage of the larger FIFO size, but I wouldn't expect incorrect behavior.

**Comment by mciantyre** [comment]
> If we can't use the common functionality, then we can remove ForceCommonBlock. Then, if the 1180's LPUART block doesn't immediately compile with the imxrt-hal lpuart driver, we could try patching it with svdtool / raltool so that it builds.

I'm giving this a try [here](https://github.com/imxrt-rs/imxrt-ral/commit/3ecda5868fcadfcf3669a7a3e4072a82da96d25e). The first thing I notice is that `FIFO[TXOF]` and `FIFO[RXUF]` are marked read only in the RAL. I'm not sure where that's coming from; they're clearly marked read-write in the (original and patched) SVD.

Once we figure that out, the 1180's LPUART block will compile in imxrt-hal. I'll come back to this tomorrow.

**Comment by korken89** [comment]
Sounds good! What I'm referring to is that the constants for FIFO depth were generated though they're for the RT1180, I would have expected the constants from the RT1011 from which the LPUART block is picked.

I'm prepping a PR for "Idle line" support where I use this, I'll ship it soon :tm:

**Comment by korken89** [comment]
Alright it was me that misunderstood the RM, the FIFO is not deep as I got the impression of.
